canopy/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.introduction, name="introduction"),
    path("chapter-1/", views.chapter1, name="chapter1"),
]

talent/urls.py
from django.urls import path

from .views import (
    UpdateProfileView,
    get_skills,
    get_current_skills,
    get_expertise,
    get_current_expertise,
    list_skill_and_expertise,
    TalentPortfolio,
    status_and_points,
    CreateFeedbackView,
    UpdateFeedbackView,
    DeleteFeedbackView,
    CreateBountyDeliveryAttemptView,
    BountyDeliveryAttemptDetail,
)

urlpatterns = [
    path(
        "portfolio/<str:username>", TalentPortfolio.as_view(), name="portfolio"
    ),
    path("profile/<int:pk>/", UpdateProfileView.as_view(), name="profile"),
    path("get-skills/", get_skills, name="get_skills"),
    path("get-current-skills/", get_current_skills, name="get_current_skills"),
    path("get-expertise/", get_expertise, name="get_expertise"),
    path(
        "get-current-expertise/",
        get_current_expertise,
        name="get_current_expertise",
    ),
    path(
        "list-skill-and-expertise/",
        list_skill_and_expertise,
        name="list-skill-and-expertise",
    ),
    path("status-and-points", status_and_points, name="status-and-points"),
    path(
        "feedback/create/",
        CreateFeedbackView.as_view(),
        name="create-feedback",
    ),
    path(
        "feedback/update/<int:pk>/",
        UpdateFeedbackView.as_view(),
        name="update-feedback",
    ),
    path(
        "feedback/delete/<int:pk>",
        DeleteFeedbackView.as_view(),
        name="delete-feedback",
    ),
    path(
        "bounty-delivery-attempt/create/",
        CreateBountyDeliveryAttemptView.as_view(),
        name="create-bounty-delivery-attempt",
    ),
    path(
        "bounty-delivery-attempt/<int:pk>/",
        BountyDeliveryAttemptDetail.as_view(),
        name="bounty-delivery-attempt-detail",
    ),
]

talent/models.py
import os
from datetime import date
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.translation import gettext_lazy as _
from treebeard.mp_tree import MP_Node

from openunited.settings.base import MEDIA_URL, PERSON_PHOTO_UPLOAD_TO
from openunited.mixins import TimeStampMixin, UUIDMixin, AncestryMixin
from engagement.models import Notification
import engagement


class Person(TimeStampMixin):
    full_name = models.CharField(max_length=256)
    preferred_name = models.CharField(max_length=128)
    user = models.OneToOneField(
        "security.User", on_delete=models.CASCADE, related_name="person"
    )
    products = GenericRelation("product_management.Product")
    photo = models.ImageField(
        upload_to=PERSON_PHOTO_UPLOAD_TO, null=True, blank=True
    )
    headline = models.TextField()
    overview = models.TextField(blank=True)
    location = models.TextField(max_length=128, null=True, blank=True)
    send_me_bounties = models.BooleanField(default=True)
    current_position = models.CharField(max_length=256, null=True, blank=True)
    twitter_link = models.URLField(null=True, blank=True, default="")
    linkedin_link = models.URLField(null=True, blank=True)
    github_link = models.URLField(null=True, blank=True)
    website_link = models.URLField(null=True, blank=True)
    completed_profile = models.BooleanField(default=False)

    class Meta:
        db_table = "talent_person"
        verbose_name_plural = "People"

    def get_initial_data(self):
        initial = {
            "full_name": self.full_name,
            "preferred_name": self.preferred_name,
            "headline": self.headline,
            "overview": self.overview,
            "github_link": self.github_link,
            "twitter_link": self.twitter_link,
            "linkedin_link": self.linkedin_link,
            "website_link": self.website_link,
            "send_me_bounties": self.send_me_bounties,
            "current_position": self.current_position,
            "location": self.location,
        }
        return initial

    def get_username(self):
        return self.user.username if self.user else ""

    def get_photo_url(self):
        image_url = MEDIA_URL + PERSON_PHOTO_UPLOAD_TO + "profile-empty.png"

        if self.photo:
            image_url = self.photo.url

        return image_url

    def get_products(self):
        return self.products.all()

    def get_absolute_url(self):
        return reverse("portfolio", args=(self.user.username,))

    def delete_photo(self) -> None:
        path = self.photo.path
        if os.path.exists(path):
            os.remove(path)

        self.photo.delete(save=True)

    def toggle_bounties(self):
        self.send_me_bounties = not self.send_me_bounties
        self.save()

    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.preferred_name

    def __str__(self):
        return self.full_name


class Status(models.Model):
    DRONE = "Drone"
    HONEYBEE = "Honeybee"
    TRUSTED_BEE = "Trusted Bee"
    QUEEN_BEE = "Queen Bee"
    BEEKEEPER = "Beekeeper"

    STATUS_CHOICES = [
        (DRONE, "Drone"),
        (HONEYBEE, "Honeybee"),
        (TRUSTED_BEE, "Trusted Bee"),
        (QUEEN_BEE, "Queen Bee"),
        (BEEKEEPER, "Beekeeper"),
    ]

    STATUS_POINT_MAPPING = {
        DRONE: 0,
        HONEYBEE: 50,
        TRUSTED_BEE: 500,
        QUEEN_BEE: 2000,
        BEEKEEPER: 8000,
    }

    STATUS_PRIVILEGES_MAPPING = {
        DRONE: _(
            "Earn points by completing bounties, submitting Ideas & Bugs"
        ),
        HONEYBEE: _(
            "Earn payment for payment-eligible bounties on openunited.com"
        ),
        TRUSTED_BEE: _("Early Access to claim top tasks"),
        QUEEN_BEE: _(
            "A grant of 1000 points for your own open product on OpenUnited"
        ),
        BEEKEEPER: _("Invite new products to openunited.com and grant points"),
    }

    person = models.OneToOneField(
        Person, on_delete=models.CASCADE, related_name="status"
    )
    name = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default=DRONE
    )
    points = models.PositiveIntegerField(default=0)

    def get_status_from_points(self, provided_points=None):
        if provided_points is None:
            provided_points = self.points

        for status in reversed(Status.STATUS_POINT_MAPPING.keys()):
            current_points = Status.STATUS_POINT_MAPPING.get(status)
            if current_points <= provided_points:
                return status

        return Status.DRONE

    def add_points(self, points):
        self.points += points
        expected_status = self.get_status_from_points()
        if self.name != expected_status:
            self.name = expected_status

        self.save()

    @classmethod
    def get_privileges(cls, status: str) -> str:
        return cls.STATUS_PRIVILEGES_MAPPING.get(status)

    @classmethod
    def get_statuses(cls) -> list:
        return list(cls.STATUS_POINT_MAPPING.keys())

    @classmethod
    def get_display_points(cls, status: str) -> str:
        statuses = cls.get_statuses()

        # if `status` is the last one in `statuses`
        if status == statuses[-1]:
            return f">= {cls.get_points_for_status(status)}"

        # +1 is to get the next status
        index = statuses.index(status) + 1
        return f"< {cls.get_points_for_status(statuses[index])}"

    @classmethod
    def get_points_for_status(cls, status: str) -> str:
        return cls.STATUS_POINT_MAPPING.get(status)

    def __str__(self):
        return f"{self.name} - {self.points}"


class PersonWebsite(models.Model):
    WebsiteType = ((0, "Personal"), (1, "Company"))
    website = models.CharField(max_length=200)
    type = models.IntegerField(choices=WebsiteType)
    person = models.ForeignKey(
        Person,
        blank=True,
        null=True,
        default=None,
        on_delete=models.CASCADE,
        related_name="websites",
    )


class PersonSkill(models.Model):
    person = models.ForeignKey(
        Person,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        default=None,
        related_name="skills",
    )
    # The below two fields contain a list of integers
    # ie. ids of skills and expertise such as [45, 56, 87]
    skill = models.JSONField(blank=True, null=True)
    expertise = models.JSONField(blank=True, null=True)

    def __str__(self):
        return f"{self.person} - {self.skill} - {self.expertise}"


class Skill(AncestryMixin):
    parent = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        default=None,
        related_name="children",
    )
    active = models.BooleanField(default=False, db_index=True)
    selectable = models.BooleanField(default=False)
    display_boost_factor = models.PositiveSmallIntegerField(default=1)
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    @staticmethod
    def get_active_skills(active=True, parent=None):
        return Skill.objects.filter(active=active, parent=parent).all()

    @staticmethod
    def get_active_skill_list(active=True):
        return Skill.objects.filter(active=active, parent=None).values(
            "id", "name"
        )


class Expertise(AncestryMixin):
    parent = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        default=None,
        related_name="expertise_children",
    )
    skill = models.ForeignKey(
        Skill,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=None,
        related_name="skill_expertise",
    )
    selectable = models.BooleanField(default=False)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    @staticmethod
    def get_skill_expertise(skill):
        return Expertise.objects.filter(skill=skill).values("id", "name")

    @staticmethod
    def get_all_expertise(parent=None):
        return Expertise.objects.filter(parent=parent).all()

    @staticmethod
    def get_all_expertise_list():
        return Expertise.objects.filter(parent=None).values("id", "name")


class BountyClaim(TimeStampMixin, UUIDMixin):
    CLAIM_TYPE_DONE = 0
    CLAIM_TYPE_ACTIVE = 1
    CLAIM_TYPE_FAILED = 2
    CLAIM_TYPE_IN_REVIEW = 3

    CLAIM_TYPE = (
        (CLAIM_TYPE_DONE, "Done"),
        (CLAIM_TYPE_ACTIVE, "Active"),
        (CLAIM_TYPE_FAILED, "Failed"),
        (CLAIM_TYPE_IN_REVIEW, "In review"),
    )
    bounty = models.ForeignKey(
        "product_management.Bounty", on_delete=models.CASCADE
    )
    person = models.ForeignKey(
        Person, on_delete=models.CASCADE, blank=True, null=True
    )
    expected_finish_date = models.DateField(default=date.today)
    kind = models.IntegerField(choices=CLAIM_TYPE, default=0)

    def get_challenge_detail_url(self):
        return self.bounty.challenge.get_absolute_url()

    def get_product_detail_url(self):
        return self.bounty.challenge.product.get_absolute_url()

    def save(self, *args, **kwargs):
        if self.kind == self.CLAIM_TYPE_DONE:
            self.person.status.add_points(self.bounty.points)

        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.bounty.challenge}: {self.person} ({self.get_kind_display()})"


class Comment(MP_Node):
    person = models.ForeignKey(
        Person, on_delete=models.CASCADE, blank=True, null=True
    )
    text = models.TextField(max_length=1000)

talent/templates/talent/bounty_claim_attempt.html
{% extends 'base.html' %}

{% block title %}Work Submission{% endblock %}

{% block content %}

<!--
  This example requires some changes to your config:
  
  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ],
  }
  ```
-->
<!-- todo: add error handling -->
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="space-y-12">
        <div class="border-b border-gray-900/10 pb-12">
            <h2 class="text-base font-semibold leading-7 text-gray-900">Submit Your Work</h2>
            <p class="mt-1 text-sm leading-6 text-gray-600">Fill out the below form to submit your work.</p>

            <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-5">

                <div class="col-span-3">
                    <label for="{{ form.bounty_claim.id_for_label }}"
                        class="block text-sm font-medium leading-6 text-gray-900">{{ form.bounty_claim.label }}</label>
                    {{ form.bounty_claim }}
                </div>

                <div class="col-span-3">
                    <label for="{{ form.delivery_message.id_for_label }}"
                        class="block text-sm font-medium leading-6 text-gray-900">{{ form.delivery_message.label }}</label>
                    <div class="mt-2">
                        {{ form.delivery_message }}
                    </div>
                    <p class="mt-3 text-sm leading-6 text-gray-600">Provide necessary information about your work.</p>
                </div>

                <div class="col-span-3">
                    <label for="{{ form.attachment.id_for_label }}"
                        class="block text-sm font-medium leading-6 text-gray-900">{{ form.attachment.label }}</label>
                    <div class="mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">
                        <div class="text-center">
                            <svg class="mx-auto h-12 w-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor"
                                aria-hidden="true">
                                <path fill-rule="evenodd"
                                    d="M1.5 6a2.25 2.25 0 012.25-2.25h16.5A2.25 2.25 0 0122.5 6v12a2.25 2.25 0 01-2.25 2.25H3.75A2.25 2.25 0 011.5 18V6zM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0021 18v-1.94l-2.69-2.689a1.5 1.5 0 00-2.12 0l-.88.879.97.97a.75.75 0 11-1.06 1.06l-5.16-5.159a1.5 1.5 0 00-2.12 0L3 16.061zm10.125-7.81a1.125 1.125 0 112.25 0 1.125 1.125 0 01-2.25 0z"
                                    clip-rule="evenodd" />
                            </svg>
                            <div class="mt-4 flex text-sm leading-6 text-gray-600">
                                <label for="{{ form.attachment.id_for_label }}"
                                    class="relative cursor-pointer rounded-md bg-white font-semibold text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 hover:text-indigo-500">
                                    <span>Upload a file</span>
                                    {{ form.attachment }}
                                </label>
                                <p class="pl-1">or drag and drop</p>
                            </div>
                            <p class="text-xs leading-5 text-gray-600">PDF, Word up to 10MB</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-6 flex items-center justify-end gap-x-6">
        <a href="javascript:history.go(-1)" class="text-sm font-semibold leading-6 text-gray-900">Cancel</a>
        <button type="submit"
            class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Save</button>
    </div>
</form>

{% endblock %}

talent/templates/talent/profile.html
{% extends 'base.html' %}

{% block media %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/choices.js@9.0.1/public/assets/styles/choices.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/treeselectjs@0.9.2/dist/treeselectjs.css" />
{% endblock %}

{% block title %}My Profile{% endblock %}

{% block content %}
{% include 'talent/partials/profile_form.html' %}
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/treeselectjs@0.9.2/dist/treeselectjs.umd.js"></script>
<script src="{{ static('scripts/tree-select.js') }}"></script>
{% endblock %}

talent/templates/talent/profile_picture.html
<div id="profile-picture" class="flex items-center shrink-0 flex-col lg:w-[244px]">
    <div id="profile-picture-placeholder"
        class="w-40 h-40 flex items-center justify-center rounded-full bg-no-repeat bg-center bg-cover"
        style="background-image: url('{{ photo_url }}')">
    </div>
    <img id="image-preview" src="" alt="Image Preview" 
        class="w-40 h-40 flex items-center justify-center rounded-full bg-no-repeat bg-center bg-cover hidden" />
    <div class="flex flex-col items-center">
        <div class="flex items-center space-x-[18px] mt-4">
            <label for="{{ form.photo.id_for_label }}"
                class="mt-4 appearance-none inline-flex items-center w-full sm:w-fit bg-white text-sm font-semibold leading-6 transition-all delay-600 rounded px-2.5 md:px-3.5 py-1.5 text-gray-900 shadow-sm hover:bg-gray-900/[0.8] hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-transparent cursor-pointer border border-solid border-[#ddd] hover:border-gray-900/[0.8]">
                {{ form.photo }}
                <span class="w-[14px] h-[14px] mr-2 inline-flex items-center justify-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <g clip-path="url(#clip0_201_4079)">
                            <g clip-path="url(#clip1_201_4079)">
                                <path
                                    d="M3.02681 10.7502C3.05806 10.7502 3.08931 10.7471 3.12056 10.7424L5.74868 10.2815C5.77993 10.2752 5.80962 10.2612 5.83149 10.2377L12.4549 3.61428C12.4694 3.59982 12.4809 3.58265 12.4888 3.56375C12.4966 3.54485 12.5006 3.52458 12.5006 3.50412C12.5006 3.48366 12.4966 3.46339 12.4888 3.44449C12.4809 3.42559 12.4694 3.40842 12.4549 3.39396L9.85806 0.795526C9.82837 0.765839 9.78931 0.750214 9.74712 0.750214C9.70493 0.750214 9.66587 0.765839 9.63618 0.795526L3.01274 7.41896C2.98931 7.4424 2.97524 7.47053 2.96899 7.50178L2.50806 10.1299C2.49286 10.2136 2.49829 10.2998 2.52388 10.3809C2.54947 10.462 2.59445 10.5357 2.65493 10.5955C2.75806 10.6955 2.88774 10.7502 3.02681 10.7502ZM4.07993 8.02521L9.74712 2.35959L10.8924 3.5049L5.22524 9.17053L3.83618 9.41584L4.07993 8.02521ZM12.7502 12.0627H1.25024C0.973682 12.0627 0.750244 12.2862 0.750244 12.5627V13.1252C0.750244 13.194 0.806494 13.2502 0.875244 13.2502H13.1252C13.194 13.2502 13.2502 13.194 13.2502 13.1252V12.5627C13.2502 12.2862 13.0268 12.0627 12.7502 12.0627Z"
                                    class="fill-current" />
                            </g>
                        </g>
                        <defs>
                            <clipPath id="clip0_201_4079">
                                <rect width="14" height="14" fill="white" />
                            </clipPath>
                            <clipPath id="clip1_201_4079">
                                <rect width="14" height="14" fill="white" />
                            </clipPath>
                        </defs>
                    </svg>
                </span>
                Upload
            </label>

            <label for="remove_picture_button" id="label_remove_picture_button"
                class="mt-4 appearance-none inline-flex items-center w-full sm:w-fit bg-white text-sm font-semibold leading-6 transition-all delay-600 rounded px-2.5 md:px-3.5 py-1.5 text-gray-900 shadow-sm hover:bg-gray-900/[0.8] hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-transparent cursor-pointer border border-solid border-[#ddd] hover:border-gray-900/[0.8]">
                <input id="remove_picture_button" type="submit" hx-get="{{ url('profile', args=(pk,)) }}" hx-target="#profile-picture" hx-confirm="Are you sure to remove the picture?"
                    class="hidden appearance-none inline-flex items-center w-full sm:w-fit bg-white text-sm font-semibold leading-6 transition-all delay-600 rounded px-2.5 md:px-3.5 py-1.5 text-gray-900 shadow-sm hover:bg-gray-900/[0.8] hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-transparent cursor-pointer border border-solid border-[#ddd] hover:border-gray-900/[0.8]">
                <span class="w-[14px] h-[14px] mr-2 inline-flex items-center justify-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="13" height="14" viewBox="0 0 13 14" fill="none">
                        <path
                            d="M4.01643 1.51526H3.87793C3.95411 1.51526 4.01643 1.45356 4.01643 1.37815V1.51526H9.27934V1.37815C9.27934 1.45356 9.34167 1.51526 9.41784 1.51526H9.27934V2.74928H10.5258V1.37815C10.5258 0.773142 10.029 0.28125 9.41784 0.28125H3.87793C3.26681 0.28125 2.76995 0.773142 2.76995 1.37815V2.74928H4.01643V1.51526ZM12.7418 2.74928H0.553991C0.247565 2.74928 0 2.99437 0 3.29773V3.84618C0 3.92159 0.0623239 3.98329 0.138498 3.98329H1.18415L1.61177 12.947C1.63947 13.5315 2.12767 13.9925 2.71802 13.9925H10.5778C11.1698 13.9925 11.6563 13.5332 11.684 12.947L12.1116 3.98329H13.1573C13.2334 3.98329 13.2958 3.92159 13.2958 3.84618V3.29773C13.2958 2.99437 13.0482 2.74928 12.7418 2.74928ZM10.4445 12.7585H2.85132L2.43236 3.98329H10.8634L10.4445 12.7585Z"
                            class="fill-current" />
                    </svg>
                </span>
                Remove
            </label>
        </div>
    </div>
</div>

<script>
document.querySelector("#id_photo").addEventListener("change", function (e) {
    const fileInput = e.target

    const imagePreview = document.getElementById("image-preview")
    const placeholder = document.getElementById("profile-picture-placeholder")
    const removeButton = document.getElementById("label_remove_picture_button")

    if (fileInput.files && fileInput.files[0]) {
        const reader = new FileReader()

        reader.onload = function (event) {
            imagePreview.src = event.target.result
            imagePreview.classList.remove("hidden")
            placeholder.style.display = "none"
            if (removeButton) {
                removeButton.style.display = "none"
            }
        }

        reader.readAsDataURL(fileInput.files[0])
    } else {
        imagePreview.src = ""
        imagePreview.style.display = "none"
    }
})

</script>